apiVersion: v1
kind: Service
metadata:
  name: kycnow
  namespace: clarilab
  labels:
    app: clarilab
    component: kycnow
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: clarilab
    component: kycnow
